service: my-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
      Resource: arn:aws:dynamodb:us-east-1:701491313159:table/clientes  

functions:
  getAllClientes:
    handler: handler.getAllClientes
    events:
      - httpApi:
          path: /clientes
          method: get

outputs:
  HttpApiUrl:
    Description: "HTTP API endpoint URL"
    Value:
      Fn::Sub: "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
